(()=>{
const NOTE_PC={C:0,'C#':1,Db:1,D:2,'D#':3,Eb:3,E:4,F:5,'F#':6,Gb:6,G:7,'G#':8,Ab:8,A:9,'A#':10,Bb:10,B:11};
const QUAL={maj:[0,4,7],min:[0,3,7],m:[0,3,7],maj7:[0,4,7,11],m7:[0,3,7,10],min7:[0,3,7,10],maj9:[0,4,7,11,14],m9:[0,3,7,10,14],min9:[0,3,7,10,14],7:[0,4,7,10],9:[0,4,7,10,14],13:[0,4,7,10,14,21],sus4:[0,5,7],'13sus':[0,5,7,10,14,21],dim:[0,3,6],dim7:[0,3,6,9],m7b5:[0,3,6,10],aug:[0,4,8],maj7sharp11:[0,4,7,11,18],'7alt':[0,4,7,10,13,15]};
const PRESETS={
 'Piano':{wave:'triangle',harm:[1,.32,.12],attack:.008,decay:.85,release:.15},
 'Electric Piano':{wave:'sine',harm:[1,.22,.10,.05],attack:.012,decay:1.2,release:.28},
 'Soft Synth':{wave:'sine',harm:[1,.15],attack:.035,decay:1.4,release:.35},
 'Warm Pad':{wave:'sine',harm:[1,.18,.06],attack:.18,decay:2.2,release:.7},
 'Bright Keys':{wave:'triangle',harm:[1,.45,.22,.10],attack:.006,decay:.75,release:.16}
};
const IS_IPHONE=/iPhone|iPod/.test(navigator.userAgent);
let ctx=null,master=null,volume=.72,bpm=96,preset='Electric Piano',ready=false,lastA=null,lastB=null,abFlip=false,active=[];
function AC(){return window.AudioContext||window.webkitAudioContext}
function stopAll(){const now=ctx?.currentTime||0;for(const x of active.splice(0)){try{x.g.gain.cancelScheduledValues(now);x.g.gain.setTargetAtTime(.0001,now,.015)}catch(e){}try{x.o.stop(now+.04)}catch(e){}}}
async function unlock(){const C=AC();if(!C)throw new Error('Web Audio unavailable');if(!ctx){ctx=new C();master=ctx.createGain();master.gain.value=volume;master.connect(ctx.destination)}if(ctx.state==='suspended')await ctx.resume();ready=true;updateStatus();return ctx}
function hz(m){return 440*Math.pow(2,(m-69)/12)}
function normalizeQ(s='maj'){let q=String(s).replace(/♭/g,'b').replace(/♯/g,'#').replace(/#/g,'sharp').toLowerCase();if(q.includes('maj7#11'))return'maj7sharp11';if(q.includes('13sus'))return'13sus';if(q.includes('7alt'))return'7alt';if(q.includes('m7b5')||q.includes('ø'))return'm7b5';if(q.includes('dim7')||q.includes('°7'))return'dim7';if(q.includes('dim')||q.includes('°'))return'dim';if(q.includes('maj9'))return'maj9';if(q.includes('maj7'))return'maj7';if(q.includes('min9')||q.includes('m9'))return'min9';if(q.includes('min7')||q.includes('m7'))return'min7';if(q.includes('sus'))return'sus4';if(q.includes('13'))return'13';if(q.includes('9'))return'9';if(q.includes('7'))return'7';if(q.includes('min')||(/^m(?!aj)/).test(q))return'min';return'maj'}
function parseLabel(s){s=String(s||'').trim();const m=s.match(/^([A-Ga-g])([#b]?)(.*)$/);if(!m)return null;const pc=NOTE_PC[m[1].toUpperCase()+m[2]];if(pc==null)return null;return{pc,q:normalizeQ(m[3])}}
function chordSpec(ch,keyPc=0){if(Array.isArray(ch)&&typeof ch[0]==='number'){const DEG=[0,2,4,5,7,9,11];return{pc:(keyPc+DEG[ch[0]%7]+12)%12,q:normalizeQ(ch[1])}}if(typeof ch==='string')return parseLabel(ch);if(ch&&typeof ch==='object'){if(Array.isArray(ch.notes)&&ch.notes.length&&typeof ch.notes[0]==='number')return{notes:ch.notes};let pc=ch.pc??ch.rootPc??ch.pitchClass??ch.root;if(typeof pc==='string')pc=NOTE_PC[pc]??parseLabel(pc)?.pc;if(typeof pc==='number')return{pc:(pc+12)%12,q:normalizeQ(ch.sym||ch.quality||ch.q||ch.type||'maj')};try{if(typeof window.chordName==='function'){const p=parseLabel(window.chordName(ch));if(p)return p}}catch(e){}}return null}
function midiFor(ch,keyPc=0,base=48){const s=chordSpec(ch,keyPc);if(!s)return[60,64,67];if(s.notes)return s.notes.slice();const ints=QUAL[s.q]||QUAL.maj;let root=base+s.pc;while(root<45)root+=12;while(root>59)root-=12;return ints.map(i=>root+i)}
function synthNote(m,t,d,amp=.11){const p=PRESETS[preset]||PRESETS['Electric Piano'];const harmonics=IS_IPHONE?p.harm.slice(0,1):p.harm;harmonics.forEach((h,k)=>{const o=ctx.createOscillator(),g=ctx.createGain(),f=hz(m)*(k+1);o.type=p.wave;o.frequency.setValueAtTime(f,t);const a=Math.max(.0001,amp*h/(1+k*.28));g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(a,t+p.attack);g.gain.exponentialRampToValueAtTime(Math.max(.0001,a*.24),t+Math.min(d*.7,p.decay));g.gain.exponentialRampToValueAtTime(.0001,t+d+Math.min(p.release,IS_IPHONE?.12:p.release));o.connect(g).connect(master);active.push({o,g});o.onended=()=>{const i=active.findIndex(x=>x.o===o);if(i>=0)active.splice(i,1);try{o.disconnect();g.disconnect()}catch(e){}};o.start(t);o.stop(t+d+Math.min(p.release,IS_IPHONE?.12:p.release)+.03)})}
function playMidiChord(notes,t,d){const use=IS_IPHONE?notes.slice(0,5):notes;const gain=1/Math.max(1,Math.sqrt(use.length));use.forEach((m,i)=>synthNote(m,t,d,.12*gain*(i===0?1.12:1)))}
async function playSequence(seq,opt={}){await unlock();stopAll();const keyPc=opt.keyPc||0,beat=60/bpm,step=opt.step||beat*2,dur=Math.min(step*.82,opt.duration||1.05),start=ctx.currentTime+.05;seq.forEach((ch,i)=>{const notes=opt.midi?ch:midiFor(ch,keyPc,opt.base||48);playMidiChord(notes,start+i*step,dur)});return true}
async function playChord(ch,opt={}){return playSequence([ch],opt)}
function setVolume(v){volume=Math.max(0,Math.min(1,+v||0));if(master)master.gain.setTargetAtTime(volume,ctx.currentTime,.02);syncControls()}
function setBpm(v){bpm=Math.max(45,Math.min(220,+v||96));syncControls()}
function setPreset(v){if(PRESETS[v])preset=v;syncControls()}
function saveAB(which,seq,opt={}){if(which==='A')lastA={seq,opt};else lastB={seq,opt};updateAB()}
async function compareAB(){const x=abFlip?lastB:lastA;abFlip=!abFlip;if(x)await playSequence(x.seq,x.opt);updateAB()}
function updateStatus(){const e=document.getElementById('crmAudioStatus');if(e){e.textContent=ready?'AUDIO READY ✓':'ENABLE AUDIO';e.classList.toggle('ready',ready)}}
function updateAB(){const e=document.getElementById('crmAB');if(e)e.textContent=`A/B ${abFlip?'B':'A'}${lastA?' · A✓':''}${lastB?' · B✓':''}`}
function syncControls(){const v=document.getElementById('crmVol'),b=document.getElementById('crmBpm'),p=document.getElementById('crmSound');if(v)v.value=Math.round(volume*100);if(b)b.value=bpm;if(p)p.value=preset}
function mount(){if(document.getElementById('crmAudioDock'))return;const d=document.createElement('div');d.id='crmAudioDock';d.innerHTML=`<style>#crmAudioDock{position:sticky;top:0;z-index:9999;background:rgba(8,11,14,.96);backdrop-filter:blur(12px);border-bottom:1px solid #29323b;padding:8px 12px;font-family:-apple-system,BlinkMacSystemFont,sans-serif;color:#eef2f6;display:flex;gap:8px;align-items:center;flex-wrap:wrap}#crmAudioDock button,#crmAudioDock select,#crmAudioDock input{min-height:40px;border-radius:10px;border:1px solid #35404b;background:#151b21;color:#eef2f6;padding:7px 10px;font-size:14px}#crmAudioDock button{font-weight:800}#crmAudioStatus{background:#d4a83d!important;color:#111!important;border:0!important}#crmAudioStatus.ready{background:#2b6845!important;color:#fff!important}.crmSmall{font-size:11px;color:#94a0ac}.crmRange{width:90px}@media(max-width:700px){#crmAudioDock{position:sticky;gap:6px}#crmAudioDock button,#crmAudioDock select{font-size:13px;min-height:42px}.crmRange{width:70px}}</style><button id="crmAudioStatus">ENABLE AUDIO</button><select id="crmSound">${Object.keys(PRESETS).map(x=>`<option>${x}</option>`).join('')}</select><span class="crmSmall">VOL</span><input class="crmRange" id="crmVol" type="range" min="0" max="100" value="72"><span class="crmSmall">BPM</span><input id="crmBpm" type="number" min="45" max="220" value="96" style="width:62px"><button id="crmTest">TEST</button><button id="crmAB">A/B A</button>`;document.body.insertBefore(d,document.body.firstChild);d.querySelector('#crmAudioStatus').onclick=async()=>{try{await unlock();await playChord('Cmaj9')}catch(e){alert('Audio could not start: '+e.message)}};d.querySelector('#crmTest').onclick=async()=>{try{await playSequence(['Cmaj7','Am7','Dm7','G7'])}catch(e){alert('Audio could not start')}};d.querySelector('#crmSound').onchange=e=>setPreset(e.target.value);d.querySelector('#crmVol').oninput=e=>setVolume(+e.target.value/100);d.querySelector('#crmBpm').onchange=e=>setBpm(e.target.value);d.querySelector('#crmAB').onclick=compareAB;syncControls();updateStatus();updateAB()}
window.CRMAudio={unlock,playChord,playSequence,midiFor,setVolume,setBpm,setPreset,stop:stopAll,saveA:(s,o)=>saveAB('A',s,o),saveB:(s,o)=>saveAB('B',s,o),compareAB,get state(){return{ready,volume,bpm,preset,active:active.length}}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();