(()=>{
const ROOTS=['C','C#','D','Eb','E','F','F#','G','Ab','A','Bb','B'];
const PC={C:0,'C#':1,Db:1,D:2,'D#':3,Eb:3,E:4,F:5,'F#':6,Gb:6,G:7,'G#':8,Ab:8,A:9,'A#':10,Bb:10,B:11};
const QUAL={maj:[0,4,7],min:[0,3,7],maj7:[0,4,7,11],min7:[0,3,7,10],maj9:[0,4,7,11,14],min9:[0,3,7,10,14],7:[0,4,7,10],13:[0,4,7,10,14,21]};
let ctx,key=0,prog=[[0,'maj7'],[5,'min7'],[1,'min7'],[4,'7']],mode='SMOOTH',top='FREE',bass='ROOT',spread=52;
const DEG=[0,2,4,5,7,9,11];
function name(n){return ROOTS[(n+120)%12]}
function label(ch){let [d,q]=ch,r=(key+DEG[d%7])%12,s={maj:'',min:'m',maj7:'maj7',min7:'m7',maj9:'maj9',min9:'m9',7:'7',13:'13'}[q]||q;return name(r)+s}
function baseNotes(ch){let [d,q]=ch,r=48+key+DEG[d%7],ints=QUAL[q]||QUAL.maj7;return ints.map(x=>r+x)}
function variants(ch){let n=baseNotes(ch),out=[];for(let inv=0;inv<Math.min(n.length,4);inv++){let a=n.slice();for(let i=0;i<inv;i++)a[i]+=12;a.sort((x,y)=>x-y);out.push(a)}let open=n.map((x,i)=>i&&i%2?x+12:x).sort((a,b)=>a-b);out.push(open);if(n.length>=4){let drop=n.slice();drop[drop.length-2]-=12;out.push(drop.sort((a,b)=>a-b))}return out}
function cost(a,b){if(!a)return 0;let aa=a.slice(),bb=b.slice(),m=Math.min(aa.length,bb.length),c=0;for(let i=0;i<m;i++)c+=Math.abs(aa[i]-bb[i]);return c+Math.abs(aa.length-bb.length)*4}
function choose(ch,prev,idx){let vs=variants(ch);if(mode==='ROOT')return vs[0];if(mode==='OPEN')return vs[Math.min(4,vs.length-1)];if(mode==='HIGH')return vs[0].map(x=>x+12);if(mode==='LOW')return vs[0].map(x=>x-12);let best=vs[0],bc=1e9;for(const v of vs){let vv=v.slice();if(top==='ASCEND'&&idx)while(prev&&vv[vv.length-1]<=prev[prev.length-1])vv=vv.map(x=>x+12);if(top==='DESCEND'&&idx)while(prev&&vv[vv.length-1]>=prev[prev.length-1])vv=vv.map(x=>x-12);let c=cost(prev,vv);if(c<bc){bc=c;best=vv}}return best}
function voicings(){let out=[],prev=null;prog.forEach((ch,i)=>{let v=choose(ch,prev,i);if(bass==='PEDAL'){let pedal=36+key;v=[pedal,...v.filter(x=>x!==pedal)]}else if(bass==='DESCEND'&&i){let target=(out[i-1][0]-1);while(target<36)target+=12;v=[target,...v.slice(1)]}out.push(v);prev=v});return out}
function hz(m){return 440*Math.pow(2,(m-69)/12)}
function play(notes,t,d=.85){ctx=ctx||new (window.AudioContext||window.webkitAudioContext)();notes.forEach((m,i)=>{let o=ctx.createOscillator(),g=ctx.createGain();o.type=i===0?'triangle':'sine';o.frequency.value=hz(m);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(i===0?.055:.035,t+.025);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g).connect(ctx.destination);o.start(t);o.stop(t+d+.05)})}
function hear(){ctx=ctx||new (window.AudioContext||window.webkitAudioContext)();let t=ctx.currentTime+.04;voicings().forEach(v=>{play(v,t);t+=.92})}
function noteText(m){return name(m%12)+(Math.floor(m/12)-1)}
function render(){let row=document.getElementById('vlRows');if(!row)return;let vs=voicings();row.innerHTML=vs.map((v,i)=>`<div class="vlChord"><div class="vlChordName">${label(prog[i])}</div><div class="vlNotes">${v.map(noteText).join(' · ')}</div><div class="vlStack">${v.slice().reverse().map((m,j)=>`<span style="margin-left:${Math.max(0,(m-v[0])*spread/36)}px">${noteText(m)}</span>`).join('')}</div><button data-i="${i}">HEAR VOICING</button></div>`).join('');row.querySelectorAll('button').forEach(b=>b.onclick=()=>{ctx=ctx||new (window.AudioContext||window.webkitAudioContext)();play(vs[+b.dataset.i],ctx.currentTime+.03,1.2)})}
function mount(){if(document.getElementById('voicingLab'))return;let s=document.createElement('section');s.id='voicingLab';s.innerHTML=`<style>#voicingLab{max-width:1180px;margin:24px auto 90px;padding:0 18px;font-family:-apple-system,BlinkMacSystemFont,sans-serif;color:#eef2f6}#voicingLab .vlHead{display:flex;justify-content:space-between;align-items:end;gap:12px;flex-wrap:wrap}#voicingLab h2{margin:0;font-size:25px}.vlSub{color:#9aa6b2;margin:5px 0 16px}.vlControls{display:flex;gap:9px;flex-wrap:wrap;margin-bottom:15px}.vlControls select,.vlControls button{font-size:16px;min-height:44px;background:#151a20;color:#eef2f6;border:1px solid #35404b;border-radius:12px;padding:9px 12px}.vlControls button{background:#f1bd4c;color:#111;font-weight:850;border:0}.vlRows{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:12px}.vlChord{background:#10151a;border:1px solid #303943;border-radius:17px;padding:14px;min-height:190px}.vlChordName{font-size:22px;font-weight:850}.vlNotes{font-size:13px;color:#aab5bf;margin:4px 0 10px}.vlStack{height:82px;display:flex;flex-direction:column;justify-content:center;gap:2px;overflow:hidden}.vlStack span{display:block;width:max-content;padding:2px 7px;border-radius:8px;background:#202832;font-size:12px}.vlChord button{min-height:42px;border:0;border-radius:10px;background:#242d36;color:#e8eef4;font-weight:750}@media(max-width:700px){#voicingLab{padding:0 12px}.vlRows{grid-template-columns:1fr}.vlChord{min-height:160px}.vlControls>*{flex:1 1 45%;font-size:15px}}</style><div class="vlHead"><div><h2>VOICING & VOICE LEADING LAB</h2><div class="vlSub">同じコード進行を、音の配置・高さ・トップノート・ベースの動きで別世界にします。</div></div></div><div class="vlControls"><select id="vlKey">${ROOTS.map((x,i)=>`<option value="${i}">Key ${x}</option>`).join('')}</select><select id="vlMode"><option>SMOOTH</option><option>ROOT</option><option>OPEN</option><option>HIGH</option><option>LOW</option></select><select id="vlTop"><option value="FREE">Top: Free</option><option value="ASCEND">Top: Ascend</option><option value="DESCEND">Top: Descend</option></select><select id="vlBass"><option value="ROOT">Bass: Root</option><option value="PEDAL">Bass: Pedal</option><option value="DESCEND">Bass: Descend</option></select><button id="vlHear">▶ HEAR PROGRESSION</button></div><div class="vlRows" id="vlRows"></div>`;document.body.appendChild(s);s.querySelector('#vlKey').onchange=e=>{key=+e.target.value;render()};s.querySelector('#vlMode').onchange=e=>{mode=e.target.value;render()};s.querySelector('#vlTop').onchange=e=>{top=e.target.value;render()};s.querySelector('#vlBass').onchange=e=>{bass=e.target.value;render()};s.querySelector('#vlHear').onclick=hear;render()}
window.CRMVoicingLab={setProgression(p){if(Array.isArray(p)&&p.length){prog=p;render()}},render};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(mount,1450));else setTimeout(mount,1450);
})();