(()=>{
let seq=['Cmaj7','Am7','Dm7','G7'],title='Current / selected progression',mounted=false,visible=false,pending=false;
const MOBILE=matchMedia('(max-width:700px)').matches||/iPhone|iPod/i.test(navigator.userAgent);
const COLORS=['#f2bd4d','#77c5ff','#a98bff','#79d99b','#ff8fb1','#f08b63'];
function midi(ch){try{if(window.CRMAudio?.midiFor)return CRMAudio.midiFor(ch,0,48)}catch(e){}return[60,64,67]}
function hz(m){return 440*Math.pow(2,(m-69)/12)}
function noteName(m){const n=['C','C#','D','Eb','E','F','F#','G','Ab','A','Bb','B'];return n[(m%12+12)%12]+(Math.floor(m/12)-1)}
function wave(notes,N=MOBILE?180:420,ms=24,phaseOffset=0){const out=new Float32Array(N),dur=ms/1000,den=Math.sqrt(Math.max(1,notes.length));for(let j=0;j<notes.length;j++){const f=hz(notes[j]),ph=phaseOffset+j*.21;for(let i=0;i<N;i++){const t=i/(N-1)*dur;out[i]+=Math.sin(2*Math.PI*f*t+ph)/den}}let pk=.001;for(let i=0;i<N;i++)pk=Math.max(pk,Math.abs(out[i]));for(let i=0;i<N;i++)out[i]/=pk;return out}
function drawWave(canvas,data,color='#f2bd4d',label=''){if(!canvas||!canvas.isConnected)return;const dpr=MOBILE?1:Math.min(2,window.devicePixelRatio||1),w=Math.max(120,Math.round(canvas.clientWidth||500)),h=Math.max(36,Math.round(canvas.clientHeight||100));canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);const c=canvas.getContext('2d',{alpha:false});c.setTransform(dpr,0,0,dpr,0,0);c.fillStyle='#10151a';c.fillRect(0,0,w,h);c.strokeStyle='#26323c';c.lineWidth=1;c.beginPath();c.moveTo(0,h/2);c.lineTo(w,h/2);c.stroke();c.strokeStyle=color;c.lineWidth=1.35;c.beginPath();for(let i=0;i<data.length;i++){const x=i/(data.length-1)*w,y=h/2-data[i]*(h*.36);i?c.lineTo(x,y):c.moveTo(x,y)}c.stroke();if(label){c.fillStyle='#95a1ad';c.font='11px -apple-system';c.fillText(label,8,14)}}
function drawChord(card,ch){const notes=midi(ch),sum=card.querySelector('.wfSum');const names=card.querySelector('.wfNames');names.textContent=notes.map(noteName).join(' · ');drawWave(sum,wave(notes,MOBILE?180:520,26),'#f2bd4d','combined waveform');if(!MOBILE){const one=card.querySelector('.wfNotes');one.innerHTML='';notes.slice(0,6).forEach((m,i)=>{const row=document.createElement('div');row.className='wfNoteRow';row.innerHTML=`<span>${noteName(m)}</span><canvas></canvas>`;one.appendChild(row);drawWave(row.querySelector('canvas'),wave([m],260,12,i*.08),COLORS[i%COLORS.length])})}}
function renderNow(){pending=false;if(!mounted||!visible)return;const host=document.getElementById('waveformLab');if(!host)return;host.querySelector('.wfTitle').textContent=title;const cards=host.querySelector('.wfCards');cards.innerHTML='';seq.slice(0,MOBILE?6:10).forEach((ch,i)=>{const d=document.createElement('div');d.className='wfCard';d.innerHTML=`<div class="wfChordTop"><strong>CHORD ${i+1} · ${ch}</strong><button>▶ HEAR</button></div><div class="wfNames"></div>${MOBILE?'':'<div class="wfLabel">INDIVIDUAL NOTES</div><div class="wfNotes"></div>'}<div class="wfLabel">COMBINED CHORD</div><canvas class="wfSum"></canvas>`;cards.appendChild(d);drawChord(d,ch);d.querySelector('button').onclick=()=>window.CRMAudio?.playChord(ch)});drawTimeline();drawFingerprint()}
function requestRender(){if(pending)return;pending=true;requestAnimationFrame(()=>requestAnimationFrame(renderNow))}
function drawTimeline(){const cv=document.getElementById('wfTimeline');if(!cv)return;const dpr=MOBILE?1:Math.min(2,devicePixelRatio||1),w=Math.max(280,Math.round(cv.clientWidth||900)),h=MOBILE?120:170;cv.width=w*dpr;cv.height=h*dpr;const c=cv.getContext('2d',{alpha:false});c.setTransform(dpr,0,0,dpr,0,0);c.fillStyle='#0f151a';c.fillRect(0,0,w,h);const use=seq.slice(0,MOBILE?6:10),gap=6,seg=(w-gap*(use.length-1))/Math.max(1,use.length);use.forEach((ch,k)=>{const data=wave(midi(ch),MOBILE?120:260,22,k*.13),x0=k*(seg+gap);c.save();c.beginPath();c.rect(x0,0,seg,h);c.clip();c.strokeStyle='#f2bd4d';c.beginPath();for(let i=0;i<data.length;i++){const x=x0+i/(data.length-1)*seg,y=h*.58-data[i]*(h*.25);i?c.lineTo(x,y):c.moveTo(x,y)}c.stroke();c.fillStyle='#cfd7df';c.font=MOBILE?'10px -apple-system':'12px -apple-system';c.fillText(`${k+1} · ${ch}`,x0+5,15);c.restore()})}
function drawFingerprint(){const cv=document.getElementById('wfFingerprint');if(!cv)return;const dpr=MOBILE?1:Math.min(2,devicePixelRatio||1),w=Math.max(280,Math.round(cv.clientWidth||900)),h=MOBILE?110:150;cv.width=w*dpr;cv.height=h*dpr;const c=cv.getContext('2d',{alpha:false});c.setTransform(dpr,0,0,dpr,0,0);c.fillStyle='#0f151a';c.fillRect(0,0,w,h);const use=seq.slice(0,MOBILE?6:10),seg=w/Math.max(1,use.length);use.forEach((ch,k)=>{const data=wave(midi(ch),MOBILE?120:240,34,k*.09),x0=k*seg;c.strokeStyle=COLORS[k%COLORS.length];c.beginPath();for(let i=0;i<data.length;i++){const px=x0+i/(data.length-1)*seg,py=h/2-data[i]*(h*.32);i?c.lineTo(px,py):c.moveTo(px,py)}c.stroke()})}
function setSequence(s,l='Selected progression'){const clean=(s||[]).map(x=>typeof x==='string'?x:(window.chordName?chordName(x):String(x))).filter(Boolean);if(clean.length){seq=clean;title=l;if(visible)requestRender()}}
function parseRoute(card){const t=card?.querySelector('.route,.paChords,.rwRoute')?.textContent||'';return t.split('→').map(x=>x.trim()).filter(Boolean)}
function mount(){if(document.getElementById('waveformLab'))return;const s=document.createElement('section');s.id='waveformLab';s.innerHTML=`<style>#waveformLab{max-width:1180px;margin:28px auto 90px;padding:0 18px;color:#eef2f6;font-family:-apple-system,BlinkMacSystemFont,sans-serif}#waveformLab h2{margin:0;font-size:25px}.wfIntro{color:#9aa6b2;margin:5px 0 14px;line-height:1.45}.wfExplain{padding:11px 13px;border:1px solid #33404a;background:#10161c;border-radius:13px;font-size:13px;color:#bac5ce;margin-bottom:14px}.wfCards{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:12px}.wfCard{background:#10151a;border:1px solid #2e3942;border-radius:16px;padding:13px}.wfChordTop{display:flex;justify-content:space-between;align-items:center;gap:8px}.wfChordTop button{min-height:36px;border:0;border-radius:9px;background:#202932;color:#eef2f6;font-weight:750}.wfNames{font-size:11px;color:#aab5bf;margin-top:6px}.wfLabel{font-size:10px;letter-spacing:.08em;color:#8e9aa5;margin:10px 0 5px}.wfNoteRow{display:grid;grid-template-columns:42px 1fr;gap:6px;align-items:center;font-size:11px;color:#aab5bf}.wfNoteRow canvas{width:100%;height:34px}.wfSum{width:100%;height:82px}.wfBigBox{margin-top:14px;border:1px solid #303b45;background:#0f151a;border-radius:16px;padding:13px}.wfBigBox h3{font-size:14px;margin:0 0 7px}.wfBigBox canvas{width:100%;height:150px}.wfFoot{font-size:12px;color:#8996a1;margin-top:8px;line-height:1.5}@media(max-width:700px){#waveformLab{padding:0 12px}.wfCards{grid-template-columns:1fr}.wfSum{height:64px}.wfBigBox canvas{height:115px}.wfExplain{font-size:12px}}</style><h2>WAVEFORM EXPLORER</h2><div class="wfIntro"><span class="wfTitle">Current / selected progression</span> · ${MOBILE?'iPhone light mode · combined waves only':'individual notes → combined chord → whole progression'}</div><div class="wfExplain">iPhoneではメモリ保護のため軽量表示に自動切替します。波形は画面に近づいた時だけ描画し、個別音の大量Canvasは生成しません。</div><div class="wfCards"></div><div class="wfBigBox"><h3>CHORD-BY-CHORD WAVEFORM</h3><canvas id="wfTimeline"></canvas></div><div class="wfBigBox"><h3>WHOLE PROGRESSION FINGERPRINT</h3><canvas id="wfFingerprint"></canvas><div class="wfFoot">VOICE MOTIONと合わせて、音の移動と合成波の変化を比較できます。</div></div>`;document.body.appendChild(s);mounted=true;const io=new IntersectionObserver(entries=>{visible=entries.some(e=>e.isIntersecting);if(visible)requestRender()},{rootMargin:'350px 0px'});io.observe(s)}
window.CRMWaveform={setSequence,render:requestRender};
document.addEventListener('click',e=>{const b=e.target.closest?.('.universe button,.paCard button,.rwCard button');if(!b||!/preview|hear|research/i.test(b.textContent||''))return;const card=b.closest('.universe,.paCard,.rwCard'),r=parseRoute(card);if(r.length)setSequence(r,card.querySelector('h3,.paName,.rwName')?.textContent?.trim()||'Selected progression')},true);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(mount,1900));else setTimeout(mount,1900);
})();