(()=>{
let seq=['Cmaj7','Am7','Dm7','G7'],title='Current / selected progression';
const COLORS=['#f2bd4d','#77c5ff','#a98bff','#79d99b','#ff8fb1','#f08b63'];
function midi(ch){try{if(window.CRMAudio?.midiFor)return CRMAudio.midiFor(ch,0,48)}catch(e){}return[60,64,67]}
function hz(m){return 440*Math.pow(2,(m-69)/12)}
function noteName(m){const n=['C','C#','D','Eb','E','F','F#','G','Ab','A','Bb','B'];return n[(m%12+12)%12]+(Math.floor(m/12)-1)}
function wave(notes,N=700,ms=28,phaseOffset=0){const out=new Float32Array(N),dur=ms/1000;for(let j=0;j<notes.length;j++){const f=hz(notes[j]),ph=phaseOffset+j*.21;for(let i=0;i<N;i++){const t=i/(N-1)*dur;out[i]+=Math.sin(2*Math.PI*f*t+ph)/Math.sqrt(notes.length)}}let pk=.001;for(const x of out)pk=Math.max(pk,Math.abs(x));for(let i=0;i<N;i++)out[i]/=pk;return out}
function drawWave(canvas,data,color='#f2bd4d',label=''){const dpr=Math.max(1,window.devicePixelRatio||1),w=canvas.clientWidth||500,h=canvas.clientHeight||100;canvas.width=w*dpr;canvas.height=h*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);c.clearRect(0,0,w,h);c.strokeStyle='#26323c';c.lineWidth=1;c.beginPath();c.moveTo(0,h/2);c.lineTo(w,h/2);c.stroke();c.strokeStyle=color;c.lineWidth=1.5;c.beginPath();for(let i=0;i<data.length;i++){const x=i/(data.length-1)*w,y=h/2-data[i]*(h*.38);i?c.lineTo(x,y):c.moveTo(x,y)}c.stroke();if(label){c.fillStyle='#95a1ad';c.font='11px -apple-system';c.fillText(label,8,14)}}
function drawChord(card,ch){const notes=midi(ch),one=card.querySelector('.wfNotes'),sum=card.querySelector('.wfSum');one.innerHTML='';notes.forEach((m,i)=>{const row=document.createElement('div');row.className='wfNoteRow';row.innerHTML=`<span>${noteName(m)}</span><canvas></canvas>`;one.appendChild(row);drawWave(row.querySelector('canvas'),wave([m],420,12,i*.08),COLORS[i%COLORS.length])});drawWave(sum,wave(notes,760,28),'#f2bd4d','combined waveform · 28 ms window')}
function render(){const host=document.getElementById('waveformLab');if(!host)return;host.querySelector('.wfTitle').textContent=title;const cards=host.querySelector('.wfCards');cards.innerHTML='';seq.forEach((ch,i)=>{const d=document.createElement('div');d.className='wfCard';d.innerHTML=`<div class="wfChordTop"><strong>CHORD ${i+1} · ${ch}</strong><button>▶ HEAR</button></div><div class="wfLabel">INDIVIDUAL NOTES</div><div class="wfNotes"></div><div class="wfLabel">COMBINED CHORD</div><canvas class="wfSum"></canvas>`;cards.appendChild(d);drawChord(d,ch);d.querySelector('button').onclick=()=>window.CRMAudio?.playChord(ch)});drawTimeline();drawFingerprint()}
function drawTimeline(){const cv=document.getElementById('wfTimeline');if(!cv)return;const dpr=Math.max(1,devicePixelRatio||1),w=cv.clientWidth||900,h=cv.clientHeight||180;cv.width=w*dpr;cv.height=h*dpr;const c=cv.getContext('2d');c.scale(dpr,dpr);c.clearRect(0,0,w,h);const gap=10,seg=(w-gap*(seq.length-1))/seq.length;seq.forEach((ch,k)=>{const data=wave(midi(ch),400,24,k*.13),x0=k*(seg+gap);c.save();c.beginPath();c.rect(x0,0,seg,h);c.clip();c.strokeStyle='#f2bd4d';c.lineWidth=1.3;c.beginPath();for(let i=0;i<data.length;i++){const x=x0+i/(data.length-1)*seg,y=h*.55-data[i]*(h*.25);i?c.lineTo(x,y):c.moveTo(x,y)}c.stroke();c.fillStyle='#cfd7df';c.font='12px -apple-system';c.fillText(`Chord ${k+1} · ${ch}`,x0+7,18);c.restore()});c.strokeStyle='#2b3741';c.beginPath();c.moveTo(0,h*.55);c.lineTo(w,h*.55);c.stroke()}
function drawFingerprint(){const cv=document.getElementById('wfFingerprint');if(!cv)return;const dpr=Math.max(1,devicePixelRatio||1),w=cv.clientWidth||900,h=cv.clientHeight||160;cv.width=w*dpr;cv.height=h*dpr;const c=cv.getContext('2d');c.scale(dpr,dpr);c.clearRect(0,0,w,h);let x=0,total=seq.length,seg=w/Math.max(1,total);seq.forEach((ch,k)=>{const data=wave(midi(ch),360,38,k*.09);c.strokeStyle=COLORS[k%COLORS.length];c.globalAlpha=.9;c.beginPath();for(let i=0;i<data.length;i++){const px=x+i/(data.length-1)*seg,py=h/2-data[i]*(h*.34);i?c.lineTo(px,py):c.moveTo(px,py)}c.stroke();x+=seg});c.globalAlpha=1;c.strokeStyle='#2b3741';c.beginPath();c.moveTo(0,h/2);c.lineTo(w,h/2);c.stroke()}
function setSequence(s,l='Selected progression'){const clean=(s||[]).map(x=>typeof x==='string'?x:(window.chordName?chordName(x):String(x))).filter(Boolean);if(clean.length){seq=clean;title=l;render();document.getElementById('waveformLab')?.scrollIntoView({behavior:'smooth',block:'start'})}}
function parseRoute(card){const t=card?.querySelector('.route,.paChords,.rwRoute')?.textContent||'';return t.split('→').map(x=>x.trim()).filter(Boolean)}
function mount(){if(document.getElementById('waveformLab'))return;const s=document.createElement('section');s.id='waveformLab';s.innerHTML=`<style>#waveformLab{max-width:1180px;margin:28px auto 90px;padding:0 18px;color:#eef2f6;font-family:-apple-system,BlinkMacSystemFont,sans-serif}#waveformLab h2{margin:0;font-size:25px}.wfIntro{color:#9aa6b2;margin:5px 0 14px;line-height:1.45}.wfExplain{padding:11px 13px;border:1px solid #33404a;background:#10161c;border-radius:13px;font-size:13px;color:#bac5ce;margin-bottom:14px}.wfCards{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:12px}.wfCard{background:#10151a;border:1px solid #2e3942;border-radius:16px;padding:13px}.wfChordTop{display:flex;justify-content:space-between;align-items:center;gap:8px}.wfChordTop button{min-height:36px;border:0;border-radius:9px;background:#202932;color:#eef2f6;font-weight:750}.wfLabel{font-size:10px;letter-spacing:.08em;color:#8e9aa5;margin:10px 0 5px}.wfNoteRow{display:grid;grid-template-columns:42px 1fr;gap:6px;align-items:center;font-size:11px;color:#aab5bf}.wfNoteRow canvas{width:100%;height:40px}.wfSum{width:100%;height:100px}.wfBigBox{margin-top:14px;border:1px solid #303b45;background:#0f151a;border-radius:16px;padding:13px}.wfBigBox h3{font-size:14px;margin:0 0 7px}.wfBigBox canvas{width:100%;height:170px}.wfFoot{font-size:12px;color:#8996a1;margin-top:8px;line-height:1.5}@media(max-width:700px){#waveformLab{padding:0 12px}.wfCards{grid-template-columns:1fr}.wfBigBox canvas{height:140px}}</style><h2>WAVEFORM EXPLORER</h2><div class="wfIntro"><span class="wfTitle">Current / selected progression</span> · individual notes → combined chord → Chord 1 / 2 / 3 / 4 → whole progression</div><div class="wfExplain">波形は「コードの良し悪し」そのものではなく、音高・Voicing・音色・位相が合成された結果です。ここでは同じ条件で比較して、響きの密度や複雑さの変化を見る研究表示として使います。</div><div class="wfCards"></div><div class="wfBigBox"><h3>CHORD-BY-CHORD WAVEFORM · 進行すると形がどう変わるか</h3><canvas id="wfTimeline"></canvas></div><div class="wfBigBox"><h3>WHOLE PROGRESSION FINGERPRINT · Chord 1 → 2 → 3 → 4</h3><canvas id="wfFingerprint"></canvas><div class="wfFoot">各区間の色はコード番号に対応します。波形だけでなく、上のVOICE MOTIONと一緒に見ると「音の移動」と「合成波の変化」を同時に比較できます。</div></div>`;document.body.appendChild(s);render()}
window.CRMWaveform={setSequence,render};
document.addEventListener('click',e=>{const b=e.target.closest?.('.universe button,.paCard button,.rwCard button');if(!b)return;if(!/preview|hear|research/i.test(b.textContent||''))return;const card=b.closest('.universe,.paCard,.rwCard'),r=parseRoute(card);if(r.length)setSequence(r,card.querySelector('h3,.paName,.rwName')?.textContent?.trim()||'Selected progression')},true);
const mo=new MutationObserver(()=>{if(!document.getElementById('waveformLab'))mount()});mo.observe(document.documentElement,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(mount,1700));else setTimeout(mount,1700);
})();